id: '16996187365180.6231518494816821'
definitionId: heading
styles:
  xl:
    fontSize:
      customValue: 14
      customUnit: px
      themeDefaultOverridePropertyKey: baseTextFontSize
    gridItem:
      x: 0
      y: 0
      w: 9
      h: 10
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 10
properties:
  name: productDetailsHeading
  text: Product Details
  verticalAlignment: middle
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
parentSlotId: '16996187365180.4208199998772493'
index: 0
actions: {}
slots: []
