id: '16996188228800.2534165517127298'
definitionId: detail
parentSlotId: '16996187365180.33288284040273286'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 86
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 86
properties:
  dynamicFields:
    value: []
    dataValue: |-
      [
        {
          "prop": "id",
          "type": "number",
          "primaryKey": true
        },
        "full_name",
        {
          "prop": "avatar",
          "type": "image"
        },
        {
          "prop": "email",
          "type": "link"
        }
      ]
    withData: false
  entity: '{{ui.productsTable.clickedRow.data}}'
  name: productDetails
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: ''
  containerStyles:
    withData: false
    dataValue: |-
      {
        padding: 'default',
        shadow: 'default',
        border: 'default'
      }
    value:
      padding: default
      shadow: default
      border: none
actions: {}
slots:
  - id: '16996188228800.3485198611824558'
    name: structure
    children:
      - id: '17001257727510.35681180895659326'
        definitionId: atomicNumber
        parentSlotId: '16996188228800.3485198611824558'
        styles:
          xl:
            visible: true
        properties:
          name: atomicNumber20
          prop: PRODUCT_ID
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        index: 0
        slots: []
      - id: '17001257727520.31956201146468577'
        definitionId: atomicString
        parentSlotId: '16996188228800.3485198611824558'
        styles:
          xl:
            visible: true
        properties:
          name: atomicString20
          prop: PRODUCT_NAME
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 1
        slots: []
      - id: '17001257727520.6307742204166553'
        definitionId: atomicCurrency
        parentSlotId: '16996188228800.3485198611824558'
        styles:
          xl:
            visible: true
        properties:
          name: atomicCurrency3
          prop: UNIT_PRICE
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 2
        slots: []
