id: '16996187365180.40134181462438856'
definitionId: modal
parentSlotId: '16995289137750.7457703352573224'
styles:
  xl:
    gridItem:
      x: 23
      y: 182
      w: 1
      h: 10
    buttonIconPlacement: center
    modalSize:
      widthValue: 60
      widthUnit: '%'
      heightValue: 61
      heightUnit: '%'
      minWidthValue: 0
      minWidthUnit: px
      minHeightValue: 0
      minHeightUnit: px
      maxWidthValue: none
      maxWidthUnit: null
      maxHeightValue: none
      maxHeightUnit: null
  xs:
    gridItem:
      x: 0
      y: 389
      w: 1
      h: 10
properties:
  name: productsModal
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  buttonText: ''
  buttonHidden:
    value: true
    dataValue: 'false'
    withData: false
  closeOnBackdrop: true
  closeOnEsc: true
actions: {}
slots:
  - id: '16996187365180.4208199998772493'
    name: header
    children:
      - heading4.yml
  - id: '16996187365180.33288284040273286'
    name: body
    children:
      - productstableDetail.yml
  - id: '16996187365180.020051456790246336'
    name: footer
    children: []
