storeItemList: []
metadata:
  favicon: ''
  code: |-
    <style>
      .horizontalMenu {
        padding-left: 8px;
      }

      .horizontalMenu .base-image__container,
      .horizontalMenu .base-image__container .base-image__img {
        min-height: 20px;
        min-width: 80px;
      }
    </style>
  title: Snowflake Admin
  description: ''
  breakpoints: []
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
