id: '16996138171790.039513149108402645'
definitionId: smartTable
parentSlotId: '16995289137750.7457703352573224'
styles:
  xl:
    gridItem:
      x: 8
      y: 0
      w: 16
      h: 165
  xs:
    gridItem:
      x: 0
      y: 198
      w: 24
      h: 149
properties:
  dynamicColumns:
    value: []
    dataValue: |-
      [
        {
          "prop": "id",
          "type": "number",
          "primaryKey": true
        },
        "full_name",
        {
          "prop": "avatar",
          "type": "image"
        },
        {
          "prop": "email",
          "type": "link"
        }
      ]
    withData: false
  data: '{{actions.loadProducts.data}}'
  name: productsTable
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Products
  showLoading:
    withData: true
    dataValue: '{{actions.loadProducts.loading}}'
    value: false
  limit: |
    20
  showFilter: true
  showAddAction:
    value: true
    dataValue: 'false'
    withData: false
actions:
  smartTableRowClick:
    - action: '16996187632090.9976447113183773'
      paramCode: ''
      index: 0
  smartTableCreate:
    - action: '16996286332130.19307539295029286'
      paramCode: ''
      index: 1
slots:
  - id: '16996138171790.45567105022151355'
    name: columns
    children:
      - id: '17000636585330.13893387382086742'
        definitionId: atomicNumber
        parentSlotId: '16996138171790.45567105022151355'
        styles:
          xl:
            visible: true
        properties:
          name: atomicNumber16
          prop: PRODUCT_ID
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        index: 0
        slots: []
      - id: '17000636585340.579013719336984'
        definitionId: atomicString
        parentSlotId: '16996138171790.45567105022151355'
        styles:
          xl:
            visible: true
        properties:
          name: atomicString14
          prop: PRODUCT_NAME
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 1
        slots: []
      - id: '17000636585340.9313806713429988'
        definitionId: atomicCurrency
        parentSlotId: '16996138171790.45567105022151355'
        styles:
          xl:
            visible: true
        properties:
          name: atomicCurrency
          prop: UNIT_PRICE
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 2
        slots: []
